export const TEXT_SAMPLES = [
  "the quick brown fox jumps over the lazy dog",
  "pack my box with five dozen liquor jugs",
  "how vexingly quick daft zebras jump",
  "sphinx of black quartz judge my vow",
  "two driven jocks help fax my big quiz",
  "to be or not to be that is the question",
  "all the worlds a stage and all the men and women merely players",
  "it was the best of times it was the worst of times",
  "call me ishmael some years ago never mind how long precisely",
  "in a hole in the ground there lived a hobbit",
  "my cat walked on my keyboard and now i own seventeen nft giraffes",
  "why do programmers prefer dark mode because light attracts bugs",
  "i told my computer i needed a break and now it wont stop sending me kit kat ads",
  "it is a truth universally acknowledged that a single man must be in want of wifi",
  "all happy families are alike but each unhappy family is unhappy in its own way",
  "in the beginning the universe was created this has made many people angry",
  "the bees are in my walls they whisper about the moon cheese conspiracy",
  "i replaced my blood with energy drinks and now i can see through time",
  "yesterday my toaster looked at me funny so i apologized to it immediately",
  "seven fuzzy wombats danced the tango in my refrigerator at midnight",
  "the sentient sock drawer demands sacrifice in the form of unmatched pairs",
  "quantum pickles exist in all jars simultaneously until observed by hungry eyes",
  "the cheese stands alone but it has excellent posture and a five year plan",
  "if you read this sentence backwards you will summon a very confused librarian",
  "my brain is just a hamster on a wheel powered by caffeine and anxiety",
  "the mitochondria is the powerhouse of the cell and also my emotional support organelle",
  "i have ninety nine problems and they are all tabs i refuse to close",
  "beware the ides of march and also tuesdays tuesdays are suspicious",
  "the ducks are watching they know what you did last summer and they are judging",
  "toasted bread is just bread that has gone through a traumatic experience",
  "i accidentally trained my pet rock to sit stay and now it wont leave",
  "documentation is a love letter that you write to your future self",
  "there are only two hard things in computer science cache invalidation and naming things",
  "the elevator to success is out of order youll have to use the stairs one step at a time",
  "my password is the last eight digits of pi just kidding its hunter two",
  "i am not lazy i am on energy saving mode like a sloth with excellent wifi",
  "error four zero four motivation not found please insert coffee and try again",
  "roses are red violets are blue unexpected semicolon on line thirty two",
  "it is not who i am underneath but what i do that defines me batman probably debugging",
  "to infinity and beyond said buzz lightyear before his server crashed",
  "i find your lack of faith disturbing also your indentation is inconsistent",
  "i am your father said the legacy codebase to the junior developer",
  "hasta la vista baby terminator debugging a memory leak probably",
  "the bananas in the fruit bowl have unionized and are demanding better lighting",
  "i have been to the year three thousand not much has changed but they live underwater",
  "my left shoe keeps manifesting in parallel universes and refuses to send postcards",
  "the refrigerator light is a government surveillance device run by sentient vegetables",
  "i taught my houseplant the meaning of existential dread and now it only grows sideways",
  "time is a flat circle and my alarm clock is a traitor who works for the sun",
  "i swallowed a dictionary yesterday and now my thoughts are alphabetized by volume",
  "the moon is just the suns backup drive and the stars are loading animations",
  "if vegetables are so good why do they keep trying to escape my crisper drawer",
  "my shadow filed a formal complaint about my posture and now i walk like a question mark",
  "cloud computing is just sky servers raining data everywhere please wear a hat",
  "the conspiracy is true giraffes are just tall government wifi antennas with spots",
  "i replaced my skeleton with spaghetti and now i am legally classified as dinner",
  "my reflection winked at me first so technically i was the one being hit on",
  "the alphabet is just twenty six different ways to scream into the void politely",
  "every time i blink a new conspiracy theory is born about what happened while i was gone",
];

export function getRandomSample(): string {
  const sample = TEXT_SAMPLES[Math.floor(Math.random() * TEXT_SAMPLES.length)];
  return sample ?? TEXT_SAMPLES[0] ?? "";
}
